name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust Node.js version if needed

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Build the project
      - name: Build the project
        run: pnpm run build

      # Step 6: Set up Firebase CLI
      - name: Set up Firebase CLI
        uses: firebase/actions/setup-firebase@v2
        with:
          firebase_token: ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Firebase authentication token from secrets

      # Step 7: Deploy to Firebase
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
